export const FETCH_FILTER_RULES_REQUEST = "FETCH_FILTER_RULES_REQUEST";
export const FETCH_FILTER_RULES_SUCCESS = "FETCH_FILTER_RULES_SUCCESS";
export const FETCH_FILTER_RULES_FAILURE = "FETCH_FILTER_RULES_FAILURE";

export const SEARCH_MAGNETS_REQUEST = "SEARCH_MAGNETS_REQUEST";
export const SEARCH_MAGNETS_SUCCESS = "SEARCH_MAGNETS_SUCCESS";
export const SEARCH_MAGNETS_FAILURE = "SEARCH_MAGNETS_FAILURE";
