export const FETCH_FILTER_RULES_REQUEST = "FETCH_FILTER_RULES_REQUEST";
export const FETCH_FILTER_RULES_SUCCESS = "FETCH_FILTER_RULES_SUCCESS";
export const FETCH_FILTER_RULES_FAILURE = "FETCH_FILTER_RULES_FAILURE";
